#!/bin/sh
#set -x
#trap read debug
#
# ./convert >CACHE/logfile.txt 2>&1
# ./convert /path/to/file.docx
###############################################

# Determine RUNDIR, sensitive to softlinks
# From: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$RUNDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Set up environment and temp dirs for processing
printf "\n================================================================\n"
printf "$(date +"%m.%d.%Y @ %H:%M") : BEGIN \n"
printf "================================================================\n\n"

# Did we pass a single input file or is this batch?
if [ -z "$1" ]; then
	BATCHMODE=true
	printf "=== INPUT: Batch operation, Synchronizing with Google\n"
	INFOLDER="$RUNDIR/CACHE/input"
	mkdir -p "$INFOLDER"

	# Sync the google drive
	#rclone -v --drive-shared-with-me sync google:__Manuscript\ Pages "$INFOLDER"

else
	BATCHMODE=false
	INFILE="$RUNDIR/CACHE/input/$1"
	printf "=== INPUT: $INFILE\n\n"

fi

OUTFOLDER="$RUNDIR/CACHE/output"
mkdir -p "$OUTFOLDER"


# Operate on entire directory
if [ "$BATCHMODE" = true ] ; then

	# Extract the XML from out of the word documents in the folder
	printf "$(date +"%m.%d.%Y @ %H:%M") : (DOCX -> XML)\n"
	find "$INFOLDER" -name *.docx -type f -exec "$RUNDIR/_extract.sh" "$OUTFOLDER" {} \;

	# Convert the extracted files to our format
	printf "\n$(date +"%m.%d.%Y @ %H:%M") : (XML -> HTML)\n"
	find "$OUTFOLDER" -name *.xml -type f -exec "$RUNDIR/_convert.sh" {} \;

# Operate on single file
else
	# Extract the XML from out of the word documents in the folder
	printf "$(date +"%m.%d.%Y @ %H:%M") : (DOCX -> XML)\n"
	"$RUNDIR/_extract.sh" "$OUTFOLDER" "$INFILE"

	# Convert the extracted files to our format
	printf "\n$(date +"%m.%d.%Y @ %H:%M") : (XML -> HTML)\n"
	INFILE="$OUTFOLDER/$(basename "$(dirname "$INFILE")")/$(basename "$INFILE").xml"
	"$RUNDIR/_convert.sh" "$INFILE"

fi

printf "\n================================================================\n"
printf "$(date +"%m.%d.%Y @ %H:%M") : END \n"
printf "================================================================\n"
