#!/bin/bash
#

# Get rundir
# From: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$RUNDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Pull the lp dir from do, parameters recommended by do
RSYNC_EXCLUDE=$RUNDIR/rsync_exclude.txt
SRC=$1
DST=$2
OPTS=( "--rsh=ssh" "-avzhr" "--checksum" "--delete" "--exclude-from" "$RSYNC_EXCLUDE" )
rsync "${OPTS[@]}" "$SRC/" "$DST/"
