#!/bin/sh
set -x
trap read debug
###########################################################################
GOOGLE_SHARE_NAME=__Manuscript\ Pages

###########################################################################

# Determine RUNDIR, sensitive to softlinks
# From: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$RUNDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Set up environment and temp dirs for processing
printf "\n================================================================\n"
printf "$(date +"%m.%d.%Y @ %H:%M") : BEGIN \n"
printf "================================================================\n\n"

# BATCH MODE
if [ -z "$1" ]; then
	BATCHMODE=true
	printf "=== INPUT: Batch operation, Synchronizing with Google\n"
	INFOLDER="$RUNDIR/content_import/TEMP/input"
	mkdir -p "$INFOLDER"

	# Sync the google drive
	rclone -v --drive-shared-with-me sync google:"$GOOGLE_SHARE_NAME" "$INFOLDER"

# SINGLE FILE
else
	BATCHMODE=false
	INFILE="$1"
	printf "=== INPUT: $INFILE\n\n"

fi

# Set up working folder
OUTFOLDER="$RUNDIR/content_import/TEMP/output"
mkdir -p "$OUTFOLDER"


# Operate on entire directory
if [ "$BATCHMODE" = true ] ; then

	# Extract the XML from out of the word documents in the folder
	printf "$(date +"%m.%d.%Y @ %H:%M") : (DOCX -> XML)\n"
	find "$INFOLDER" -name *.docx -type f -exec "$RUNDIR/_extract.sh" "$OUTFOLDER" {} \;

	# Convert the extracted files to our format
	printf "\n$(date +"%m.%d.%Y @ %H:%M") : (XML -> HTML)\n"
	find "$OUTFOLDER" -name *.xml -type f -exec "$RUNDIR/_convert.sh" {} \;

	# Organize everything into .../folio/FOLIO_ID/[tc|tcn|tl]
	find "./content_import/TEMP/output" -name *.html -type f -exec "./content_import/_sort.sh" {} \;

# Operate on single file
else

	printf "FIXME: single file is broken, fix it!"
	exit

	# Extract the XML from out of the word documents in the folder
	printf "$(date +"%m.%d.%Y @ %H:%M") : (DOCX -> XML)\n"
	"$RUNDIR/content_import/_extract.sh" "$OUTFOLDER" "$INFILE"

	# Convert the extracted files to our format
	printf "\n$(date +"%m.%d.%Y @ %H:%M") : (XML -> HTML)\n"
	INFILE="$OUTFOLDER/$(basename "$(dirname "$INFILE")")/$(basename "$INFILE").xml"
	"$RUNDIR/content_import/_convert.sh" "$INFILE"

fi

printf "\n================================================================\n"
printf "$(date +"%m.%d.%Y @ %H:%M") : END \n"
printf "================================================================\n"
