#!/bin/bash

# Determine RUNDIR, sensitive to softlinks
# From: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$RUNDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export RUNDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

WEBROOT="$RUNDIR/../nginx/webroot"
LOG_FILE="$WEBROOT/logfile.txt"
JSON_STATUS_FILE="$WEBROOT/import_status.json"
LOCK_FILE="$RUNDIR/.lock"

write_json_status()
{
	printf '{' > $JSON_STATUS_FILE;
	printf '"start":"%s"' "$ts_start" >> $JSON_STATUS_FILE;
	printf ',' >> $JSON_STATUS_FILE;
	printf '"logfile":"%s"' "$(basename $LOG_FILE)" >> $JSON_STATUS_FILE;
	printf ',' >> $JSON_STATUS_FILE;
	printf '"progress":"%s"' "$progress" >> $JSON_STATUS_FILE;
	printf ',' >> $JSON_STATUS_FILE;
	printf '"end":"%s"' "$ts_end" >> $JSON_STATUS_FILE;
	printf '}' >> $JSON_STATUS_FILE;
}

# Makes sure we exit if flock fails.
set -e
(
    # Wait for lock for 10 seconds
    flock -n 200

	# Copy the human readable HTML in place
	yes | \cp -rf "$RUNDIR/content_import/import_status.html" "$WEBROOT"

	progress="In Progress..."
	ts_start=$(date +"%m.%d.%Y @ %H:%M")
	ts_end=''
	write_json_status

	$RUNDIR/import >$LOG_FILE 2>&1

	progress="Complete"
	ts_end=$(date +"%m.%d.%Y @ %H:%M")
	write_json_status

) 200>$LOCK_FILE
